#%RAML 1.0 Trait

queryParameters:
  email:
    type: string
    required: false
    example: "abc@gmail.com"
  phoneCountry:
    type: string
    required: false
    example: "+91"  
  phoneNumber:
    type: string
    required: false
    example: "8787898987"
  registrationDate:
    type: string
    required: false
    example: "20-12-2021"    